[theme]
primaryColor = "#ffffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
